name: Go tests
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install hurl
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/4.1.0/hurl_4.1.0_amd64.deb
          sudo apt-get update && sudo apt-get install ./hurl_4.1.0_amd64.deb
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Go (from go.mod)
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Run tests
        run: go test -race ./...
